services:
  backend:
    build: .
    ports:
      - "8080:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
      - /app/__pycache__
    command: sh -c "echo 'Запуск миграций Alembic...'; alembic upgrade head; echo 'Миграции применены. Запуск сервера...'; uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: